name: Publish documentation
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Removing as fails, to publish to github pages, merge master into gh-pages branch
    # - run: mkdir -p public && npx redoc-cli bundle doc/specs/playstrategy-api.yaml --output public/index.html --disable-google-font
    # - name: GitHub pages deploy
    #   uses: maxheld83/ghpages@68f783a4f5313d776c1599e18479607e71c9c738
    #   env:
    #     BUILD_DIR: "public/"
    #     GH_PAT: ${{ secrets.GH_PAT }}
